<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/2dc5983f48.js" crossorigin="anonymous"></script>
    <link href="./style.css" rel="stylesheet" />


    <title>Document</title>
</head>

<body>
    <header>
        
    <div class="cine">
            <i class="fas fa-film"></i>
            <H1 class="titre1">Ma Cinéthèque</h1>
    </div>
    
    <nav>

           
    <div>
            <a class="butt"  href="./liste.php">Liste</a>
            <a class="butt" href="./ajout.php">Ajout</a>
            <a class="butt"  href="./suppression.php">Suppression</a>
    <div>



        </nav>
    </header>